# Site settings
title: Praveer's Musings
email: praveer09@gmail.com
description: "This is a place where I share my learnings"
baseurl: ""
url: "http://praveer09.github.io"
username: praveer09

# Build settings
markdown: kramdown
permalink: pretty
